spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SumitSharma0106/testconfig
          clone-on-start: true
          default-label: main
          refresh-rate: 10
